baseUrl = "https://docs.iris-go.com/"
languageCode = "en-us"
title = "Iris Go Web Examples"
PygmentsCodeFences = true
PygmentsStyle = "trac"
[Params]
description = "Iris Go Web Examples provides easy to understand code snippets on how to get started with web development in the Go programming language and Iris web framework."
